version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - httphero-network

  flask:
    container_name: flask-request
    build:
      context: ./HttpHeroApi/request
      dockerfile: Dockerfile.dev
    volumes:
      - ./HttpHeroApi/request:/app
    ports:
      - "8001:5000"
    networks:
      - httphero-network
    environment:
      PORT: 5000

networks:
  httphero-network:
