version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - httphero-network

  express:
    container_name: rest-client
    build:
      context: ./HttpHeroApi
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      NODE_ENV: production
    networks:
      - httphero-network
    volumes:
      - ./HttpHeroApi:/app

networks:
  httphero-network:
